export const KEYS = {
   PERMISSION: 'PERMISSION_KEY',
   PUBLIC: 'PUBLIC_KEY',
   ROLE: 'ROLE_KEY'
}

export const PERMISSIONS = {
   ACCOUNT: {
      CREATE: 'ACCOUNT.CREATE',
      READ: 'ACCOUNT.READ',
      UPDATE: 'ACCOUNT.UPDATE',
      DELETE: 'ACCOUNT.DELETE',
      MANAGE: 'ACCOUNT.MANAGE'
   },
   ACCOUNT_ROLE: {
      CREATE: 'ACCOUNT_ROLE.CREATE',
      READ: 'ACCOUNT_ROLE.READ',
      UPDATE: 'ACCOUNT_ROLE.UPDATE',
      DELETE: 'ACCOUNT_ROLE.DELETE',
      MANAGE: 'ACCOUNT_ROLE.MANAGE'
   },
   AUTH: {
      CREATE: 'AUTH.CREATE',
      READ: 'AUTH.READ',
      UPDATE: 'AUTH.UPDATE',
      DELETE: 'AUTH.DELETE',
      MANAGE: 'AUTH.MANAGE'
   },
   LEAVE_ASSIGNMENT: {
      CREATE: 'LEAVE_ASSIGNMENT.CREATE',
      READ: 'LEAVE_ASSIGNMENT.READ',
      UPDATE: 'LEAVE_ASSIGNMENT.UPDATE',
      DELETE: 'LEAVE_ASSIGNMENT.DELETE',
      MANAGE: 'LEAVE_ASSIGNMENT.MANAGE'
   },
   LEAVE_TYPE: {
      CREATE: 'LEAVE_TYPE.CREATE',
      READ: 'LEAVE_TYPE.READ',
      UPDATE: 'LEAVE_TYPE.UPDATE',
      DELETE: 'LEAVE_TYPE.DELETE',
      MANAGE: 'LEAVE_TYPE.MANAGE'
   },
   PERMISSION: {
      CREATE: 'PERMISSION.CREATE',
      READ: 'PERMISSION.READ',
      UPDATE: 'PERMISSION.UPDATE',
      DELETE: 'PERMISSION.DELETE',
      MANAGE: 'PERMISSION.MANAGE'
   },
   STAFF: {
      CREATE: 'STAFF.CREATE',
      READ: 'STAFF.READ',
      UPDATE: 'STAFF.UPDATE',
      DELETE: 'STAFF.DELETE',
      MANAGE: 'STAFF.MANAGE'
   },
   SKILL: {
      CREATE: 'SKILL.CREATE',
      READ: 'SKILL.READ',
      UPDATE: 'SKILL.UPDATE',
      DELETE: 'SKILL.DELETE',
      MANAGE: 'SKILL.MANAGE'
   },
   SKILL_ASSIGNMENT: {
      CREATE: 'SKILL_ASSIGNMENT.CREATE',
      READ: 'SKILL_ASSIGNMENT.READ',
      UPDATE: 'SKILL_ASSIGNMENT.UPDATE',
      DELETE: 'SKILL_ASSIGNMENT.DELETE',
      MANAGE: 'SKILL_ASSIGNMENT.MANAGE'
   },
   PROJECT_TYPE: {
      CREATE: 'PROJECT_TYPE.CREATE',
      READ: 'PROJECT_TYPE.READ',
      UPDATE: 'PROJECT_TYPE.UPDATE',
      DELETE: 'PROJECT_TYPE.DELETE',
      MANAGE: 'PROJECT_TYPE.MANAGE'
   },
   PROJECT_ASSIGNMENT: {
      CREATE: 'PROJECT_ASSIGNMENT.CREATE',
      READ: 'PROJECT_ASSIGNMENT.READ',
      UPDATE: 'PROJECT_ASSIGNMENT.UPDATE',
      DELETE: 'PROJECT_ASSIGNMENT.DELETE',
      MANAGE: 'PROJECT_ASSIGNMENT.MANAGE'
   },
   ROLE: {
      CREATE: 'ROLE.CREATE',
      READ: 'ROLE.READ',
      UPDATE: 'ROLE.UPDATE',
      DELETE: 'ROLE.DELETE',
      MANAGE: 'ROLE.MANAGE'
   },
   ROLE_ASSIGNMENT: {
      CREATE: 'ROLE_ASSIGNMENT.CREATE',
      READ: 'ROLE_ASSIGNMENT.READ',
      UPDATE: 'ROLE_ASSIGNMENT.UPDATE',
      DELETE: 'ROLE_ASSIGNMENT.DELETE',
      MANAGE: 'ROLE_ASSIGNMENT.MANAGE'
   },
   PROJECT_PRICE_TYPE: {
      CREATE: 'PROJECT_PRICE_TYPE.CREATE',
      READ: 'PROJECT_PRICE_TYPE.READ',
      UPDATE: 'PROJECT_PRICE_TYPE.UPDATE',
      DELETE: 'PROJECT_PRICE_TYPE.DELETE',
      MANAGE: 'PROJECT_PRICE_TYPE.MANAGE'
   },
   FILE_STORAGE: {
      CREATE: 'FILE_STORAGE.CREATE',
      READ: 'FILE_STORAGE.READ',
      UPDATE: 'FILE_STORAGE.UPDATE',
      DELETE: 'FILE_STORAGE.DELETE',
      MANAGE: 'FILE_STORAGE.MANAGE'
   },
   PROJECT: {
      CREATE: 'PROJECT.CREATE',
      READ: 'PROJECT.READ',
      UPDATE: 'PROJECT.UPDATE',
      DELETE: 'PROJECT.DELETE',
      MANAGE: 'PROJECT.MANAGE'
   },
   JOB_POSITION: {
      CREATE: 'JOB_POSITION.CREATE',
      READ: 'JOB_POSITION.READ',
      UPDATE: 'JOB_POSITION.UPDATE',
      DELETE: 'JOB_POSITION.DELETE',
      MANAGE: 'JOB_POSITION.MANAGE'
   },
   PROJECT_ROLE: {
      CREATE: 'PROJECT_ROLE.CREATE',
      READ: 'PROJECT_ROLE.READ',
      UPDATE: 'PROJECT_ROLE.UPDATE',
      DELETE: 'PROJECT_ROLE.DELETE',
      MANAGE: 'PROJECT_ROLE.MANAGE'
   },
   JOB_LEVEL: {
      CREATE: 'JOB_LEVEL.CREATE',
      READ: 'JOB_LEVEL.READ',
      UPDATE: 'JOB_LEVEL.UPDATE',
      DELETE: 'JOB_LEVEL.DELETE',
      MANAGE: 'JOB_LEVEL.MANAGE'
   },
   DASHBOARD: {
      CREATE: 'DASHBOARD.CREATE',
      READ: 'DASHBOARD.READ',
      UPDATE: 'DASHBOARD.UPDATE',
      DELETE: 'DASHBOARD.DELETE',
      MANAGE: 'DASHBOARD.MANAGE'
   },
   SKILL_LEVEL: {
      CREATE: 'SKILL_LEVEL.CREATE',
      READ: 'SKILL_LEVEL.READ',
      UPDATE: 'SKILL_LEVEL.UPDATE',
      DELETE: 'SKILL_LEVEL.DELETE',
      MANAGE: 'SKILL_LEVEL.MANAGE'
   },
   FEATURE: {
      CREATE: 'FEATURE.CREATE',
      READ: 'FEATURE.READ',
      UPDATE: 'FEATURE.UPDATE',
      DELETE: 'FEATURE.DELETE',
      MANAGE: 'FEATURE.MANAGE'
   },
   ROLE_FEATURE_PERMISSION: {
      CREATE: 'ROLE_FEATURE_PERMISSION.CREATE',
      READ: 'ROLE_FEATURE_PERMISSION.READ',
      UPDATE: 'ROLE_FEATURE_PERMISSION.UPDATE',
      DELETE: 'ROLE_FEATURE_PERMISSION.DELETE',
      MANAGE: 'ROLE_FEATURE_PERMISSION.MANAGE'
   },
   CORE_ADMIN: 'CORE.ADMIN',
   CORE_BASIC: 'CORE.BASIC'
}

export const ROLES = {
   CORE_ADMIN: 'CORE.ADMIN',
   CORE_BASIC: 'CORE.BASIC'
}
